### ISSUE TITLE
Are Media Overlays supported?

### ISSUE THREAD

**Issue by garconvacher** [readium/r2-testapp-swift#10]
[EpubTest 0320](http://epubtest.org/epubs/epub30-test-0320-20160325.epub) test: media overlays doesn't work.

**Comment by HadrienGardeur** [comment]
This is a known issue.

Media overlays are properly parsed but we don't have support for them yet in the navigator and the test app.

**Comment by llemeurfr** [comment]
By the way, I'm always curious to know which are the real usages of EPUB media overlays. @garconvacher, what is your use case? or is it only that you've passed the EpubTest suite to check the progress on R2 swift?

**Comment by garconvacher** [comment]
Yes, I've noticed this issue while testing. I don't know the use of media overlays, but there could be an interesting use for language books for example. [PLS Lexicon](https://idpf.github.io/a11y-guidelines/content/tts/pls.html) is not implemented in app reader :(

**Comment by garconvacher** [comment]
@ManfredMuchenberger,
[Lis-a reader](https://itunes.apple.com/be/app/lis-a/id1096168122?mt=8) works fine with media overlays (MO) in ePub on iOS (at least on `<p>` level) but not on Android.
[Lea reader](https://play.google.com/store/apps/details?id=com.adilibre.leareader&hl=en) works fine on Android.

Outside Readium,
iBooks on iOS reads MO too but only with FXL.
[Reasily](https://play.google.com/store/apps/details?id=com.gmail.jxlab.app.reasily&hl=en_US) on Android reads MO.

**Comment by ManfredMuchenberger** [comment]
@garconvacher
Thank you very much for the various hints and links. These are really some apps I didn't know about and I just tried them out:

Reasily in Android: plays MO but is completely out of synch and audio is stuttering

Lea Reader in Android: seems to be a nice app!, but crashed while loading big books, plays MO nicely in smaller book with word-synch, audio interruptions while app is sturning to next page/screen, 

Lis-a reader: seems to be a nice app!, plays MO nicely with word-synch, continues audio at the end of screen but is not always turning text to next screen/page. If you turn page manually it falls out of synch.

iBooks: we knew about iBooks and its FXL limitation
