### ISSUE TITLE
Mutually incompatibility of the frameworks in Cartfile

### ISSUE THREAD

**Issue by tanmoynandi** [readium/r2-testapp-swift#100]
while updating the Carthage using `carthage update --platform ios` it gives the following error,

`Could not pick a version for github "Readium/r2-shared-swift", due to mutually incompatible requirements:
	"master"
	"develop" (github "readium/readium-opds-swift")`

Now what should I do? I am a newbie in Swift and iOS development. Need help.

**Comment by aferditamuriqi** [comment]
this might have resulted in some mixed branched of the same repo, this should be resolved and therefore I am closing this issue. should this happen again please reopen this issue and I'll take a look
