### ISSUE TITLE
regression on LCP: the app does not register anymore licenses. 

### ISSUE THREAD

**Issue by llemeurfr** [readium/r2-testapp-swift#101]
Tested with the beta3 version. Using a license in ready state. I see a status request but no registration request.

**Comment by llemeurfr** [comment]
The process is described in details in https://github.com/readium/readium-2/tree/master/other/lcp. 

It the case corresponding to the issue, I import a new license in the app. The process should involve a registration a the end of the import, just after the encrypted publication has been fetched and the license has been embedded in the publication. It seems that this is not the case anymore. 

The next time the publication is open, the app will find the license in the publication. As the app has  already registered the license, no registration is needed.

**Comment by aferditamuriqi** [comment]
handled in V1.0.0-beta.4
