### ISSUE TITLE
The app crashes if the cover is LCP encrypted

### ISSUE THREAD

**Issue by llemeurfr** [readium/r2-testapp-swift#102]
At least this is what I think. I have an LCP licence from TEA. The covers are temporarily encrypted (they will correct that asap). When I open the book, the cover that appear is "any" cover (for another book). When I try to open the book the app crashes. 

Here is the license:
{"id":"d342bf51-0d4e-4d8a-94e6-e6d53fa90e28","issued":"2018-05-10T12:44:33+00:00","updated":"2018-05-10T12:44:33+00:00","provider":"https://www.tea-ebook.com/care/","encryption":{"profile":"http://readium.org/lcp/profile-1.0","content_key":{"encrypted_value":"uUtbFQi/mTJslst1jbwFNtIHgyJusWDJxJb6/1AxRKJk/HDfNWjoAUk6M2OxgWybFU6WUFRwIpr08cgnWxj4Lg==","algorithm":"http://www.w3.org/2001/04/xmlenc#aes256-cbc"},"user_key":{"text_hint":"Please enter your e-mail from your onleihe account","algorithm":"http://www.w3.org/2001/04/xmlenc#sha256","key_check":"rV+SgWZ0u/6jWJ3XoTTTtv6XyCSTjJKzy2zJeQmoVM0nrH/hb5OXIO4OAzh/z6l8chnQPBUggPkSuRaRh2Wcgg=="}},"links":[{"rel":"self","href":"https://care-test.onleihe.de/api/publications/cb2c291338fa7fb4464a6edd04b58df65d84d5c9dd1dcd7890678b962fcf21de/licenses/d342bf51-0d4e-4d8a-94e6-e6d53fa90e28/profiles/profile-1.0","type":"application/vnd.readium.lcp.license.v1.0+json"},{"rel":"publication","href":"http://dp1.onleihe.de/downloadprovider/epub/tea/cb2c291338fa7fb4464a6edd04b58df65d84d5c9dd1dcd7890678b962fcf21de.epub","type":"application/epub+zip","hash":"b58782f5f96db9f4f0af3dfb7af68449d72925269b1b2ea3c8845016a69ef84a","length":3629000},{"rel":"status","href":"https://care-test.onleihe.de/api/publications/cb2c291338fa7fb4464a6edd04b58df65d84d5c9dd1dcd7890678b962fcf21de/licenses/d342bf51-0d4e-4d8a-94e6-e6d53fa90e28/profiles/profile-1.0/status","type":"application/vnd.readium.license.status.v1.0+json"},{"rel":"hint","href":"https://aide.tea-ebook.com/","type":"text/html"},{"rel":"https://digital-content-care.com/resources","href":"https://care-test.onleihe.de/api/publications/cb2c291338fa7fb4464a6edd04b58df65d84d5c9dd1dcd7890678b962fcf21de/licenses/d342bf51-0d4e-4d8a-94e6-e6d53fa90e28/resources{?device_id}","templated":true,"type":"application/json"}],"user":{"id":"bob"},"signature":{"algorithm":"http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha256","certificate":"MIIDJzCCAg+gAwIBAgIJANCkn+ZzcSH1MA0GCSqGSIb3DQEBCwUAMEIxEzARBgNVBAoTCmVkcmxhYi5vcmcxFzAVBgNVBAsTDmVkcmxhYi5vcmcgTENQMRIwEAYDVQQDEwlFRFJMYWIgQ0EwHhcNMTcwNjEzMTEwNjU3WhcNMTkwNjEzMjM1OTU5WjBLMRMwEQYDVQQKEwplZHJsYWIub3JnMSYwJAYDVQQLEx1SZWFkaXVtIExDUCBMaWNlbnNlIFByb3ZpZGVyczEMMAoGA1UEAxMDVEVBMIGbMBAGByqGSM49AgEGBSuBBAAjA4GGAAQAsgbyaxntdtGldtCedVjclIs8n5cjJBGpk9Sw0XRHG9qSDu8eYHoqQVtqxsUmMC6W0wy2SznAd9HzQ+oWbQ3Bj6YAgdOHLvmBmNshPv4tjxN0a3IjJ0n2rI4qz//LkQNMn5UwjS//m1hzgoYDOL7YXyf4CJ+dthirbEqgWHFIU5Lh1DijgZ4wgZswHwYDVR0jBBgwFoAU3Fz8k+Qfn+6wuupSCyvKUlzgyYcwHQYDVR0OBBYEFO72zcD0TY9GVKiCCD/YdYjMpj6KMA4GA1UdDwEB/wQEAwIHgDAJBgNVHRMEAjAAMD4GA1UdHwQ3MDUwM6AxoC+GLWh0dHA6Ly9jcmwuZWRybGFiLnRlbGVzZWMuZGUvcmwvRURSTGFiX0NBLmNybDANBgkqhkiG9w0BAQsFAAOCAQEAbOodNE0HdbpHFHu7bs4QIWyAuyxVYGqKWDag9iW+3/lOSE4wj+HKa9qrpinsCjliOp+G4zyWvYAizYaAqlZdoHG0PdeZStvCpyjKPd+qrKi4gfwXFE8W3yzk5K/3+YlCdvPafx+yVafw6TDWz6ohyRQRLIden/a3MNB9of4LY/hvgLq20uhB/PNuEYXWGmg9jTU7JQV10W3e1M77VnspzAp9NRKR9S7YF6pxmEE2Qew3UDJH+JP/B5c0KraAgj//Nm8Nl6ZxXNlc0WWwXW5Q6S+etN9dnXIxQ6NWNwwv5iUpbD49KKzfctqShlnCkeVqCPS1FQOsoXg5zpTmCEGnTw==","value":"AZWE3hI3u4Z2zovMDvtAFM4vlYVEI1LTL5iWg0PNE2+iBvwOK/LqifoGDrDUkiPeUlQBIyY/4g2pasCx4Bxx4cvGAaXWRNoXqjv7sv9AqnW+Ycc9rGFbGPPZRCbSQKUybp0+4Xl6XJSyiX1/qhUewsXT4rMkTRbfItcIDyRaOPG6TqNV"}}

**Comment by iaomw** [comment]
It will always fail with 404 not found when fetching status document. Impossible to get the book.

`{ URL: https://care-test.onleihe.de/api/publications/cb2c291338fa7fb4464a6edd04b58df65d84d5c9dd1dcd7890678b962fcf21de/licenses/d342bf51-0d4e-4d8a-94e6-e6d53fa90e28/profiles/profile-1.0/status } { Status Code: 404, Headers {\n    Age =     (\n        0\n    );\n    \"Cache-Control\" =     (\n        \"private, must-revalidate\"\n    );\n    Connection =     (\n        \"keep-alive\"\n    );\n    \"Content-Length\" =     (\n        471\n    );\n    \"Content-Type\" =     (\n        \"text/html; charset=UTF-8\"\n    );\n    Date =     (\n        \"Tue, 29 May 2018 09:08:26 GMT\"\n    );\n    Expires =     (\n        \"-1\"\n    );\n    \"Keep-Alive\" =     (\n        \"timeout=10\"\n    );\n    Pragma =     (\n        \"no-cache\"\n    );\n    Server =     (\n        nginx\n    );\n    Vary =     (\n        \"Accept-Encoding\"\n    );\n    \"X-Cache\" =     (\n        MISS\n    );\n    \"X-Cacheable\" =     (\n        NO\n    );\n    \"X-Varnish\" =     (\n        44241743\n    );\n    \"X-Varnish-IP\" =     (\n        \"127.0.0.1\"\n    );\n} })`

**Comment by llemeurfr** [comment]
TEA has corrected the issue on encrypted covers by re-creating the content database. The current publication doesn't exist anymore, thus the 404. We are trying to see if an EPUB file that was given to us before the correction was applied is causing the same trouble.

**Comment by mmenu-mantano** [comment]
It doesn't crash right now in the testapp. I made a test EPUB with an encrypted cover to check:
https://www.dropbox.com/s/s2hlp0x1wvds2qz/epub-encrypted-cover.epub?dl=0
