### ISSUE TITLE
[a11y] Focus on continuous reading

### ISSUE THREAD

**Issue by gregoriopellegrino** [readium/r2-testapp-swift#105]
The focus doesn't follow the reading voice (when it changes page).

Tested on iOS 11.3 with VoiceOver

**Comment by mmenu-mantano** [comment]
Now that scroll-mode will be forced by https://github.com/readium/r2-navigator-swift/pull/56, it should follow properly the text. Except when a paragraph is longer than the screen, then the WebView scrolls only when reaching the next paragraph. This is the default WebView behavior and I don't think we can change that.
