### ISSUE TITLE
[a11y] Half pages while reading

### ISSUE THREAD

**Issue by gregoriopellegrino** [readium/r2-testapp-swift#109]
When the focus changes during the reading, two half pages are shown as in the picture below:
![image](https://user-images.githubusercontent.com/5065125/40040815-11101a02-581c-11e8-9877-150b00c311c4.png)

Tested on iOS 11.3 with VoiceOver

**Comment by mmenu-mantano** [comment]
This PR https://github.com/readium/r2-navigator-swift/pull/56 forces scroll-mode when VoiceOver is activated, which should fix this issue.
