### ISSUE TITLE
Want to list my own epub files which is fetched from remote url.

### ISSUE THREAD

**Issue by Sptibo** [readium/r2-testapp-swift#113]
Recently in my case r2-testapp-swift project is listing 6 epub file on bookshelf screen (1.epub, 2.epub..so on, From Samples folder).
Now I have few Urls of epub files. How do I show my files instead of showing those sample files?

**Comment by mickael-menu** [comment]
I believe this is out-of-scope for Readium SDK.

The `testapp` project is only an example app here to get you started quickly, you should be able to modify its code to fit your needs.
