### ISSUE TITLE
The app should open the publication if the status document is unreachable

### ISSUE THREAD

**Issue by llemeurfr** [readium/r2-testapp-swift#114]
Currently we see an Error message "The JSON is no representing a valid Status Document." / OK and the publication is not opened. 
In case of an http 404, we should see a warning "The Readium LCP License Status Document does not exist." / OK and the publication should still be opened. 
In case of an http 5xx, the message should be "The Readium LCP server is experiencing problems, the License Status Document is unreachable" / OK and the publication should still be opened.

**Comment by aferditamuriqi** [comment]
closes with PR https://github.com/readium/r2-lcp-swift/pull/12
