### ISSUE TITLE
The dome project can not be build--carthage fail to build scheme "readium-lcp-swift"

### ISSUE THREAD

**Issue by ClassWizard** [readium/r2-testapp-swift#12]
When I run "carthage update --platform ios" on my terminal. It failed with exit code 65.

> *** Building scheme "readium-lcp-swift" in readium-lcp-swift.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/cdsz_ios_dev3/ClassWizard/项目/GitDemo/r2-testapp-swift/Carthage/Checkouts/readium-lcp-swift/readium-lcp-swift.xcodeproj -scheme readium-lcp-swift -configuration Release -derivedDataPath /Users/cdsz_ios_dev3/Library/Caches/org.carthage.CarthageKit/DerivedData/9.1_9B55/readium-lcp-swift/74ce4880060c402a53a020ec7ef60cbaf99e35a7 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath ./ SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO (launched in /Users/cdsz_ios_dev3/ClassWizard/项目/GitDemo/r2-testapp-swift/Carthage/Checkouts/readium-lcp-swift)
This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/x9/31mjtwpx06s8h52qchtd_mf80000gn/T/carthage-xcodebuild.mkZdCa.log
cdsz-ios-dev3tekiiMac:r2-testapp-swift cdsz_ios_dev3$ 

Then I checked the log:

> /Users/cdsz_ios_dev3/ClassWizard/项目/GitDemo/r2-testapp-swift/Carthage/Checkouts/readium-lcp-swift/readium-lcp-swift/LcpSession.swift:11:8: error: module file's minimum deployment target is ios11.1 v11.1: /Users/cdsz_ios_dev3/ClassWizard/项目/GitDemo/r2-testapp-swift/Carthage/Checkouts/readium-lcp-swift/Carthage/Build/iOS/ZIPFoundation.framework/Modules/ZIPFoundation.swiftmodule/arm64.swiftmodule
import ZIPFoundation
             ^
** ARCHIVE FAILED **
The following build commands failed:
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
	CompileSwift normal arm64
(2 failures)

It seems that the minimum deployment target of ZIPFoundation.framework was not set.

I noticed that "readium-lcp-swift" has changed ZIPFoundation's dependence 3 days ago.

[https://github.com/readium/readium-lcp-swift/commit/74ce4880060c402a53a020ec7ef60cbaf99e35a7](url)

These are all I knew by Now. How can I fix it?

**Comment by camill-a** [comment]
Hi @ClassWizard,
I'm aware of it and currently replacing ZIPFoundation by ZIP. ZIPFoundation is not carthage compatible and Swift 4 hence it was a private fork being used in the project, bad choice.

I'll let you know when this is pushed

**Comment by ClassWizard** [comment]
Thank you very much!
Besides, I want to use your SDK in my project. Can I just start with the Readium-2 or should I use the Readium-SDK. I noticed that your Readium-2 for Android Version should be completed by the end of this year.

**Comment by llemeurfr** [comment]
Hi ClassWizard, 
Good to know that you're interested in our developments. Even if the Readium-2 project is quite young, if you don't have to distribute a full featured (I mean with media overlays etc.) reading app by the end of this year, it may be easier for you to work on Readium-2. If you're tied to a quick launch, the current mature Readium SDK may be better. In such a case pls read the dual-license of the Readium SDK and  check it works for you. 
If you adopt Readium-2, just know that we're building a community of developers around it, who will help getting it ready quicker. If you can/will help, please contact Readium or EDRLab.

**Comment by camill-a** [comment]
Hi @ClassWizard,
Everything should be in order now. LCP WiP is now on a branch and the repo is stable, as it should have been. Let me know if you encounter any other issues.

**Comment by ClassWizard** [comment]
Hi  @camill-a 
Thanks a lot. It works. Now I can run the dome.
