### ISSUE TITLE
UX: display a toast notification after a publication has been imported 

### ISSUE THREAD

**Issue by llemeurfr** [readium/r2-testapp-swift#121]
This is for discussion. IMO,  after a publication has been imported in "my library", we should change the alert (modal box) for a toast notification, using the most standard UI iOS provides. 

Please provide samples of what we can find in other apps and let's choose.

**Comment by aferditamuriqi** [comment]
Toast is not really something that is standard iOS UI, but I think with some minimal effort we could add some self disappearing notification for this matter

**Comment by aferditamuriqi** [comment]
this could be achieved with something like this:

```
  func showAlertMessage(title: String?, message: String?) {
    let alertController = UIAlertController(title: title, message: message, preferredStyle: .alert)
    self.present(alertController, animated: true, completion: nil)
    DispatchQueue.main.asyncAfter(deadline: .now() + .seconds(3)) {
      alertController.dismiss(animated: true, completion: nil)
    }
  }
```

and used like this:

`    self.showAlertMessage(title: "Download Complete", message: nil)
`

![ios notification](https://user-images.githubusercontent.com/17150623/42057249-c3c540d2-7aea-11e8-846e-11ce18bf62d9.png)

**Comment by llemeurfr** [comment]
Duplicate. Treated is issue #40
