### ISSUE TITLE
compile error with xcode9.2

### ISSUE THREAD

**Issue by risechen** [readium/r2-testapp-swift#13]
The appdelegate can't be compiled with the xcode9.2.
The detail is below:
Value of tuple type 'PubBox' (aka '(publication: Publication, associatedContainer: Container)') has no member 'protectedBy'
![image](https://user-images.githubusercontent.com/31931021/34474057-6bbbc082-ef3f-11e7-9467-2c059a2320e8.png)

**Comment by odinforce** [comment]
Same issue here.

**Comment by amerdababneh** [comment]
Same issue here as well.

**Comment by iosDevEdrlab** [comment]
Hello @risechen @odinforce @amerdababneh ,

`item.0.associatedContainer.drm` The protectedBy has to be replaced by `associatedContainer.drm`. I pushed the update on the Shared repo but not on testapp, will be pushed today

**Comment by llemeurfr** [comment]
By the way, Readium-2 developers are invited to join the Readium Slack to exchange on their developments, by using the auto-invite on https://readium-slack.herokuapp.com/.

**Comment by amerdababneh** [comment]
Thanks
