### ISSUE TITLE
UI: when reopening a book, we land between columns

### ISSUE THREAD

**Issue by aferditamuriqi** [readium/r2-testapp-swift#147]
I have this issue on:

iOS 11.3.1 iPhone 7 Plus
iOS 11.4 iPhone X

**Comment by aferditamuriqi** [comment]
yes, here it is
![img_0079](https://user-images.githubusercontent.com/17150623/42581205-3a2ec982-84fa-11e8-8475-bee3ea16088b.JPG)

**Comment by HadrienGardeur** [comment]
I've had this issue as well, but only after updating to the latest version on TestFlight. It only happened once (after the update).

**Comment by gbugniot** [comment]
I'm able to reproduce the issue on a device and on a simulator by changing device orientation while reading a book.

**Comment by gbugniot** [comment]
It seems that this issue it not completely fixed.

I'm able to reproduce the problem by following these steps:
- Open in portrait mode a reflowable EPUB
- Scroll right to be in a middle of an chapter / html file
- Navigate back to the bookshelf
- Open, still in portrait mode, another reflowable EPUB
- Rotate the device to landscape mode
- Navigate back to the bookshelf
- Rotate the device to portrait mode
- Open again the first epub

It will land between columns, you have to swipe left or right to return in a normal position.
