### ISSUE TITLE
turning pages on tap (left/right) doesn't work on iPad

### ISSUE THREAD

**Issue by aferditamuriqi** [readium/r2-testapp-swift#16]
swipe works just fine in both landscape and portrait mode.

**Comment by aferditamuriqi** [comment]
I have some more info on this: 
iOS 9.x: no taps
iOS 10.x: taps are working 
iOS 11.x: taps are working as well

we still have the issue in Landscape on 10.x + 
when the chapter end in odd page number, right tap is in the center of the screen

**Comment by HadrienGardeur** [comment]
We might want to move such issues to the new r2-glue-js repo, since this is entirely tied to the JS that we inject in those test apps. Thoughts?

**Comment by aferditamuriqi** [comment]
you're correct, wasn't sure if this would be just a JS issue, since it seems to be only in iOS 9 though

**Comment by HadrienGardeur** [comment]
Taps are 100% implemented in JS while swipe is handled by the native code (you're either scrolling a webviews with snap points, or the scroll view that contains the webviews).

IMO on iOS the issue could be:

- tied to JS itself
- tied to the native callback in the JS

Can we migrate it to the new repo?

**Comment by aferditamuriqi** [comment]
yes i will migrate it.

**Comment by aferditamuriqi** [comment]
This issue was moved to readium/r2-glue-js#2
