### ISSUE TITLE
Trigger Element is not supported

### ISSUE THREAD

**Issue by rkwright** [readium/r2-testapp-swift#166]
[EPUBTEST 0100 - Reflowable Content Tests](http://epubtest.org/epubs/epub30-test-0100-20160116.epub) tests the trigger functionality in EPUB.  This feature is apparently unimplemented.  While this feature may be deprecated in EPUB 3.2 (when we get it done) but it was valid in EPUB 3.0.*.

To reproduce:
1. Open the test file.
2. Navigate to the specified test.
3. Press the button.  

Nothing happens.

**Comment by HadrienGardeur** [comment]
I don't think that we currently have any plans for supporting them.

Can we agree on this and potentially close this issue?

**Comment by llemeurfr** [comment]
Switch is [deprecated in EPUB 3.2](https://w3c.github.io/publ-epub-revision/epub32/spec/epub-changes.html#sec-cdoc-switch) and Readium will not support it.
