### ISSUE TITLE
Switch and Fallbacks not supported

### ISSUE THREAD

**Issue by rkwright** [readium/r2-testapp-swift#169]
Both of these features of EPUB are not supported in the app.  While they are already deprecated, there is content out there that uses them - though not much.

#### Steps to reproduce:
1. Download [EPUBTEST 0100 - Reflowable Content Tests](http://epubtest.org/epubs/epub30-test-0100-20160116.epub)
2. Open in the app
3. Navigate to the  "Fallbacks" section.
4. Run the tests

They all fail.

Tested with build 1.0.3

**Comment by HadrienGardeur** [comment]
I don't think that we have plans for supporting switch either. Can we agree on this and potentially close this issue?

**Comment by llemeurfr** [comment]
Switch is [deprecated in EPUB 3.2](https://w3c.github.io/publ-epub-revision/epub32/spec/epub-changes.html#sec-cdoc-switch) and Readium will not support it.
