### ISSUE TITLE
FXL publication view scale is buggy due to the navigation bar

### ISSUE THREAD

**Issue by gbugniot** [readium/r2-testapp-swift#174]
Tested with this FXL EPUB: https://drive.google.com/open?id=1qO7e7C2R6p58iyB_zPDYuDzWaDqvLUu4

If the navigation bar (the top one) is hidden, with default zoom, publication is not correctly scaled. If you want to navigate to the following page, you have to tap two times on the right side, first time to reach the edge, second time to actually trigger the scroll to the next page.

But if you perform a central tap to display the navigation bar, the publication is perfectly scale according to the space available within the view, so only one tap is required to scroll (right or left, still with the default zoom of course).

I do not encounter this issue with the FXL EPUBTEST 201 document. But according to my tests, it's seems totally related to the navigation bar. When a FXL publication is opened, the viewport fits the available space considering the navigation bar displayed. Then, the navbar is hidden automatically so the viewport is not scaled accordingly anymore.

**Comment by aferditamuriqi** [comment]
fixed here https://github.com/readium/r2-navigator-swift/pull/39
