### ISSUE TITLE
Cover image is truncated for an RTL publication

### ISSUE THREAD

**Issue by gbugniot** [readium/r2-testapp-swift#176]
The cover of epub test suite 130 publication is not correctly displayed (truncated at 70%).
However It's not the case with this publication : https://drive.google.com/open?id=11ZtWpcCGc_L0dDtqb2S0Ei2R8J5N0jVU

**Comment by mmenu-mantano** [comment]
This is a duplicate of https://github.com/readium/r2-testapp-swift/issues/187
