### ISSUE TITLE
ePagine LCP protected publication does not open

### ISSUE THREAD

**Issue by llemeurfr** [readium/r2-testapp-swift#181]
After import, the spinner runs forever.

Steps to reproduce: 
go to https://lcp.epagine.fr/
create an account
download "The city of shifting Water"
try to open it with the iOS test app.

**Comment by aferditamuriqi** [comment]
closing this issue manually, as i just saw that is was missing the closing keyword 
this issue is closed with PR https://github.com/readium/r2-testapp-swift/pull/184
