### ISSUE TITLE
EPUB ReadingSystem object not supported

### ISSUE THREAD

**Issue by rkwright** [readium/r2-testapp-swift#182]
The EPUB Reading System object does not appear to have been implemented.

#### Steps to reproduce:
1. Download [EPUBTEST 0102 - Scripting Tests](http://epubtest.org/epubs/epub30-test-0102-20160116.epub)
2. Open in the app
3. Navigate to the  "Reading System Object" section.
4. Run the tests

They all fail.

Tested with build 1.0.3

**Comment by mickael-menu** [comment]
Superseded by https://github.com/readium/r2-testapp-swift/issues/256
