### ISSUE TITLE
CFI Tests do not work in EPUB Test Suite

### ISSUE THREAD

**Issue by rkwright** [readium/r2-testapp-swift#183]
The CFI tests in the EPUB Test Suite all fail. This functionality has not apparently been implemented yet.

#### Steps to reproduce:
1. Download [EPUBTEST 0140 - CFI Tests](http://epubtest.org/epubs/epub30-test-0140-20160116.epub)
2. Open in the app
3. Run the tests

They all fail.

Tested with build 1.0.3

**Comment by mickael-menu** [comment]
We don't have any plans to support CFIs at the moment.
