### ISSUE TITLE
LCP: apps in "test" mode should refuse "production" licenses 

### ISSUE THREAD

**Issue by llemeurfr** [readium/r2-testapp-swift#185]
An application compiled in LCP "test" mode should not try to open an LCP "production" license. But an application compiled in LCP "production" mode must open both "production" and "test" licenses.

LCP "test" licences are identified by "profile":"http://readium.org/lcp/basic-profile"
and LCP "production" licenses are identified by "profile":"http://readium.org/lcp/profile-1.0"

Therefore we need a compile-time trigger, that shows a message like "The Readium LCP profile expressed in this license cannot be processed by this application."  if the profile value is not it the expected set:
- "basic-profile" for apps compiled in "test" mode
- "profile-1.0" for apps compiled in "production" mode.

**Comment by mmenu-mantano** [comment]
The "list of supported profiles" needs to be exposed by `liblcp.a` to tackle this issue. Right now in the app we don't have any way to know whether the liblcp is in test or production mode.

**Comment by mmenu-mantano** [comment]
https://github.com/readium/r2-lcp-swift/pull/42 Implements @danielweck's solution of testing a predefined prod license internally to determine whether the liblcp is in production mode or not.
