### ISSUE TITLE
Deal with vertically written publications (CJK)

### ISSUE THREAD

**Issue by llemeurfr** [readium/r2-testapp-swift#188]
Make sure that with the latest Readium CSS version CJK ebooks are displayed correctly. Both reflow and FXL. 

Jiminy has written documents about internationalization: 

https://github.com/readium/readium-css/wiki/Internationalization,-pagination-and-user-settings

https://medium.com/@jiminypan/internationalization-and-ebooks-e7b7078ba017

**Comment by llemeurfr** [comment]
If possible, CJK reflow publications should work in portrait and landscape modes. Most Asian people read in portrait mode, therefore if landscape support is difficult for any reason, we may postpone it.

**Comment by JayPanoz** [comment]
> If possible, CJK reflow publications should work in portrait and landscape modes.

Note we’re not handling “spreads” i.e. two columns in CJK – vertical writing as we simply can’t. That may have some impacts if there’s some logic tied to 2-col in horizontal writing.

**Comment by aferditamuriqi** [comment]
closing this as the associated PR has been merged https://github.com/readium/r2-testapp-swift/pull/205
