### ISSUE TITLE
r2-lcp-wrapper-swift doesn't compile

### ISSUE THREAD

**Issue by Pr0gmaT1k** [readium/r2-testapp-swift#19]
Cartage won't build [r2-lcp-wrapper-swift](https://github.com/readium/r2-lcp-wrapper-swift).
Xcode say: 
```
ld:
library not found for -llcp
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I think it probably related to [this issue](https://github.com/readium/r2-lcp-wrapper-swift/issues/1)

**Comment by llemeurfr** [comment]
@aferditamuriqi recently made lcp optional, but not I'm not certain it's already pushed.

**Comment by Pr0gmaT1k** [comment]
I manually add .a static lib and i think it does not compile at all on XCode 9.2
What is the recommended Xcode version ?

**Comment by bkg2018** [comment]
It's missing liblcp.a, which should not appear in repository anyway, but what is the 'official' way of building this static library?

**Comment by aferditamuriqi** [comment]
Actually, Carthage doesn't build with the static lib dependency. I will be removing the lcp dependencies from Carthage and provide information on how to build with lcp.  The lcp optional has been merged, but this issue related to Carthage which can't be made optional, but just commented out, i did not notice before that lcp was included in Carthage file

**Comment by llemeurfr** [comment]
We've removed the liblcp.a (basic profile, i.e. for tests) from Github, as it's weird to have a static lib in a source code repo and the lcp support is now optional in the test app. 

We've moved the r2 lcp static lib (for different platforms) to http://bit.ly/2CdJLe8, from which you can retrieve it now. Basic profile only, for tests.  The production version of the lib will replace it for official participants of the LCP ecosystem, after signature of the LCP Terms of Use.

**Comment by Pr0gmaT1k** [comment]
There is a last reference of LCP Wrapper inside the project

https://github.com/readium/r2-testapp-swift/blob/master/r2-testapp-swift/DetailsTableViewController.swift#L11

And many reference to unused frameworks.

It's just a quick clean to build and test / explore the app, may i make a pull request ?

**Comment by llemeurfr** [comment]
yes please, make a PR

**Comment by llemeurfr** [comment]
Will be dealt with in #22
