### ISSUE TITLE
Strange waving mark on vertical CJK content

### ISSUE THREAD

**Issue by iaomw** [readium/r2-testapp-swift#199]
R2Reader
![img_3116](https://user-images.githubusercontent.com/2307692/43891507-bc5b2b0e-9bc9-11e8-9149-5911cb3bf013.PNG)
iBooks
![img_3117](https://user-images.githubusercontent.com/2307692/43891508-bc75de36-9bc9-11e8-9716-f6d9268c37bc.PNG)

**Comment by JayPanoz** [comment]
Hmmm, looks like an overlapping issue because the `line-height` is solid there – that’s weird because we give more room to CJK and the default `line-height` is 20% bigger than for latin scripts. 

As for the wave I have difficulties defining whether this is [`text-emphasis-style` with a custom string](https://developer.mozilla.org/en-US/docs/Web/CSS/text-emphasis-style), [`text-underline-style: wavy`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-style) and or a `background-image` – which is [a popular technique](https://css-tricks.com/styling-underlines-web/#article-header-id-5) for such things.

**Comment by JayPanoz** [comment]
On a related note, I can also see missing characters in both screenshots (they happen to be the same one): 

![capture d ecran 2018-08-10 a 12 11 27](https://user-images.githubusercontent.com/12599652/43952589-a3ca335a-9c96-11e8-8789-adea773031ef.png)

![capture d ecran 2018-08-10 a 12 11 39](https://user-images.githubusercontent.com/12599652/43952593-a6ed19a8-9c96-11e8-82e2-50aa4f05368d.png)

**Comment by iaomw** [comment]
https://drive.google.com/file/d/1CSZXEscGXkdNharMjOknYc82CJEXyvZ1/view?usp=sharing
Testing sample

**Comment by JayPanoz** [comment]
OK so it’s a background-image

```
span.kindle-cn-specialtext-double{
	 background-image: url(../Images/image00788.gif);
	 background-repeat: repeat-y;
	 background-size:1em 1em;
	 background-position: 0% 0%;
	 padding-left: 0.15em;
	 margin-bottom: 0em ;
}
```
And here’s the GIF: 

![wavy underline](https://user-images.githubusercontent.com/12599652/45677315-2946cf00-bb34-11e8-979c-bbeb7fd6b9e4.gif)

What’s weird is that `line-height` in r2 looks like `normal` while it should be the result of https://github.com/readium/readium-css/blob/master/css/src/modules/ReadiumCSS-base.css#L38 with a compensation of 1.167 (https://github.com/readium/readium-css/blob/master/css/src/modules/ReadiumCSS-base.css#L197) 

What’s strange is that this is the `line-height` I get, which is very different from the one in the first screenshot:

![capture d ecran 2018-09-18 a 11 33 59](https://user-images.githubusercontent.com/12599652/45678507-d91d3c00-bb36-11e8-961d-5a96b03df192.png)

A couple of extra notes: 

1. the file is ePub 2 (not EPUB3)
2. it is specifically authored for Kindle (all class names start with `kindle`)
3. It is using `<meta content="vertical-rl" name="primary-writing-mode" />` (cf. [compat doc](https://github.com/readium/readium-css/blob/master/docs/CSS21-epub_compat.md#primary-writing-mode)) in addition to `page-progression-direction`.

I’m assuming this wasn’t a Kindle Mobi file converted back to EPUB as it lacks some meta artifacts you’ll typically find in such retro-conversions… but maybe I’m wrong?

**Comment by JayPanoz** [comment]
Also extra notes related to https://github.com/readium/architecture/issues/70

cc @HadrienGardeur and @llemeurfr 

If this isn’t retroconverted, that could be either an exception or the rule, in which latter case… the number of such files could be massive on markets we are not necessarily familiar with.

**Comment by mickael-menu** [comment]
From what I gather it's nothing we can fix in the Swift projects directly. Feel free to reopen the issue with more details on how to fix this in Swift if I misunderstood.
