### ISSUE TITLE
[ERROR] Failed binding IPv4 listening socket: Address already in use (48) (SWIFT)

### ISSUE THREAD

**Issue by moguncool** [readium/r2-testapp-swift#200]
Hi I add a publication to the Publication Server with swift and it works fine and opens the book, but when I navigate back to previous viewcontroller and try to a add at the new book to the Publication sever the following error occurs

So please advice how to stop the server or overcome this error

 Error while instanciating R2 Publication Server.
[ERROR] Failed binding IPv4 listening socket: Address already in use (48)

**Comment by aferditamuriqi** [comment]
This has been resolved by not using a fixed port, please try again with the latest in develop or master branch and if there are still any issues, reopen the issue with your comments.
