### ISSUE TITLE
EpubViewController - Book Title hidden in iPhone X

### ISSUE THREAD

**Issue by moguncool** [readium/r2-testapp-swift#206]
Hi, When I try to open a ePub file , the Book Title hidden is in iPhone X. Pease advice how to overcome this

**Comment by moguncool** [comment]
![screen shot 2018-08-23 at 2 45 58 pm](https://user-images.githubusercontent.com/15356745/44516819-b2104d80-a6e3-11e8-8bca-1e42d84c4e0c.png)

**Comment by HadrienGardeur** [comment]
I think this needs to be addressed with the introduction of safe areas: https://developer.apple.com/documentation/uikit/uiview/positioning_content_relative_to_the_safe_area?changes=_1

@moguncool have you tweaked this behavior in a branch or a PR yet?

**Comment by aferditamuriqi** [comment]
a similar issue was addressed here https://github.com/readium/r2-testapp-swift/issues/142 but seems like it didn't solve it entirely. (tagging the issue for reference)

**Comment by mmenu-mantano** [comment]
The PR #252 is actually removing the title label from the EPUB navigator, so it will not be an issue anymore.
Also, https://github.com/readium/r2-navigator-swift/pull/39 uses safe areas to position reflowable and fixed layout documents, so the content won't be covered by the iPhone X's screen insert. When zooming a fixed layout, the overflow goes under the insert, which is the behavior desired by Apple.
