### ISSUE TITLE
The app shows invalid publication message for a valid epub

### ISSUE THREAD

**Issue by RodPatagonia** [readium/r2-testapp-swift#210]
The app gives the following error: "The publication isn't valid" 
when importing an epub validated on http://validator.idpf.org

Please see attached screenshot

![img_0318](https://user-images.githubusercontent.com/40782598/45235552-92fee780-b2af-11e8-8a5d-505900206618.PNG)

**Comment by mmenu-mantano** [comment]
Could you please reopen the issue with a link to download the problematic EPUB? Otherwise we can't reproduce the issue. Thank you.
