### ISSUE TITLE
Task failed with exit code 65 ObjectMapper

### ISSUE THREAD

**Issue by MahavirTechuz** [readium/r2-testapp-swift#214]
Hi,
i am facing this issue when i run command carthage update --platform ios 

*** Building scheme "ObjectMapper-iOS" in ObjectMapper.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/mahavirjadav/Downloads/r2-testapp-swift-develop/Carthage/Checkouts/ObjectMapper/ObjectMapper.xcworkspace -scheme ObjectMapper-iOS -configuration Release -derivedDataPath /Users/mahavirjadav/Library/Caches/org.carthage.CarthageKit/DerivedData/10.0_10A255/ObjectMapper/2.2.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/_8/1_nh_gbn3pjcss5dgv60ynv40000gn/T/ObjectMapper SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/mahavirjadav/Downloads/r2-testapp-swift-develop/Carthage/Checkouts/ObjectMapper)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/_8/1_nh_gbn3pjcss5dgv60ynv40000gn/T/carthage-xcodebuild.jFftWW.log

**Comment by dilip-i** [comment]
For previous xcodes it was running successfully. Can you confirm that it is happening in new Xcode 10 , iOS12.?

**Comment by MahavirTechuz** [comment]
Yes I am running in Version 10.0 (10A255) & iOS 12

**Comment by dilip-i** [comment]
> Yes I am running in Version 10.0 (10A255) & iOS 12
> please tell me if you have any solution for these that would be a great help
> Thanks

Yes i have a work around. The trick is to replace the ObjectMapper in Checkouts folder with the latest ObjectMapper(https://github.com/tristanhimmelman/ObjectMapper) after "checking out" and before "building scheme". Thats it:)

**Comment by MahavirTechuz** [comment]
hi, dilip,
Can you explain steps in detail because I am still facing this issue
Thanks

**Comment by astauder** [comment]
Hi MahavirTechuz, 
I have been struggling with this for a couple of weeks now and I have a solution. 
Run    _carthage update --platform ios_   in terminal then when checking out has finished do a 
ctrl z to pause carthage, replace ObjectMapper with the new one from (https://github.com/tristanhimmelman/ObjectMapper) then in terminal type _fg carthage update --platform ios_ this will continue carthage and it finally works!

**Comment by MahavirTechuz** [comment]
Thanks, @astauder  your solution work for me and also @dilip-i  for help thanks both of you.
 I am closing this issue for now.
Thanks a lot guys,
