### ISSUE TITLE
R2LCPClient,ReadiumLCP,SiwftyJSON,ZIPFoundation,SQLite lib is Missing

### ISSUE THREAD

**Issue by risechen** [readium/r2-testapp-swift#24]
![image](https://user-images.githubusercontent.com/31931021/37270984-f00f7ace-260b-11e8-8a6f-e1a5300f36f4.png)
R2LCPClient,ReadiumLCP,SiwftyJSON,ZIPFoundation,SQLite lib is Missing,the project can't compiled

**Comment by iaomw** [comment]
Hey, if you want compile and try the demo. You can simply remove all frameworks which grayed out .
They are the dependency of LCP feature.

**Comment by dilip-i** [comment]
But how to add LCP feature, i can not find carthage supported for LCP something like R2LCPClient,ReadiumLCP

**Comment by llemeurfr** [comment]
For getting info on LCP integration, please join the Readium Slack, lcp channel. See http://readium.org/development/contributing/.
