### ISSUE TITLE
How to get the current page

### ISSUE THREAD

**Issue by kosicki123** [readium/r2-testapp-swift#251]
Hi, I would like to know how can I get the current page. For example, when I add a bookmark, I want to know which page I have added from the total pages of the book. I do have some information about the context like the current chapter progression, the current chapter index and the total number of chapters.

**Comment by mmenu-mantano** [comment]
The Locator model is not used yet on Swift, but we are working on it so it should be available soon. `position` is probably the closest to a page number you could find (and will be the actual page number for PDF and CBZ)

**Comment by kosicki123** [comment]
I see...I solved my problem checking the current href on the change page event. Thanks anyway!
