### ISSUE TITLE
The app shows invalid publication message for a valid epub

### ISSUE THREAD

**Issue by RodPatagonia** [readium/r2-testapp-swift#254]
The app gives the following error: "The publication isn't valid"
when importing an epub validated on http://validator.idpf.org
Here it is a link to the epub

https://www.dropbox.com/s/llebuto8idenhcn/612.epub?dl=0

**Comment by mmenu-mantano** [comment]
The EPUB parser is not handling properly XML namespaces in the OPF. The PR https://github.com/readium/r2-streamer-swift/pull/105 should fix that when it's finished, by replacing AEXML with Fuzi and defining custom namespace prefixes for XPath expressions.

**Comment by mmenu-mantano** [comment]
I checked this book again with https://github.com/readium/r2-streamer-swift/pull/105 and it's working properly. 👍

**Comment by RodPatagonia** [comment]
Cool Thanks a lot
