### ISSUE TITLE
LCP: Agent missing the indication of the app version

### ISSUE THREAD

**Issue by llemeurfr** [readium/r2-testapp-swift#291]
The current agent is 
r2-testapp-swift/5 CFNetwork/978.0.7 Darwin/18.7.0
A previous on was 
r2-testapp-swift/21 CFNetwork/978.0.7 Darwin/18.5.0

5 and 21 are build versions. The App version (e.G. 2.1.0) is missing, whilst it is the most interesting info expected in this string.

**Comment by mickael-menu** [comment]
This is the default `User-Agent` on iOS. Since we want to override it with a custom one, we can also add other meaningful data such as iOS version and device model. What do you think?

eg. `r2-testapp-swift/1.0 iOS/13 iPhone5,2 CFNetwork/978.0.7 Darwin/18.5.0`
