### ISSUE TITLE
LCP: remove the possibility to open a document with a cancelled license

### ISSUE THREAD

**Issue by llemeurfr** [readium/r2-testapp-swift#293]
This happens only if the license document cannot be updated (in my test case, it is because I did not generate a license from the test frontend, therefore the status document contains a broken link to the license, which is obtained via the frontend used as a proxy). 

The process must be slightly changed: if the license document cannot be updated, the status must take precedence over the initial license (which is not showing the cancellation). 

I modified the [processing model](https://github.com/readium/architecture/blob/master/other/lcp/README.md) accordingly. 

Log
- the app requests the status document
- the app tries to register (??) and receives the error  from the LCP server {"title":"Forbidden","status":403,"detail":"License is neither ready or active"}
- the frontend shows an error log when the app tries to update the license {"title":"Not Found","status":404,"detail":"Purchase not found"}

Current result: the ebook opens, it should not. Receiving the status document with a cancelled state should be enough to stop the process.

**Comment by mickael-menu** [comment]
This is essentially what we discussed on https://github.com/readium/r2-testapp-swift/issues/294, so I guess it should also be fixed now.

@llemeurfr Do you have any license to validate this particular use case?
