### ISSUE TITLE
Javascript issue with iPad Mini 4 but not with Air 2 ?

### ISSUE THREAD

**Issue by garconvacher** [readium/r2-testapp-swift#3]
Hi,
Strange issue:
I tested an epub with some JS in R2 version 0.2(2) on two iPads (iOS 11.0.2).
On iPad Air 2, JS works fine. On iPad Mini 4, it's buggy, script seems to stop. However, it works fine with iBooks or Lisa.
The script is based on [this](https://www.w3.org/TR/2016/WD-wai-aria-practices-1.1-20160317/examples/radio/radio.html)

**Comment by HadrienGardeur** [comment]
What's buggy exactly on the iPad Mini 4?

Are you having issues interacting with radio buttons?

**Comment by garconvacher** [comment]
Yes, there's no interaction at all. We'll simplify the code to find where it stops.

**Comment by HadrienGardeur** [comment]
I think that this might be related to #1 and not specifically JS support.

Right now touch handling is still very basic, and could interfere with the interactions on a page.

**Comment by garconvacher** [comment]
OK, I close this issue.
