### ISSUE TITLE
Navigation Bar title should be visible on Night mode

### ISSUE THREAD

**Issue by iaomw** [readium/r2-testapp-swift#30]
The title is not visible on black background.

**Comment by aferditamuriqi** [comment]
This is on the TOC and also DRM ViewController

**Comment by iaomw** [comment]
https://github.com/readium/r2-testapp-swift/pull/27/commits/d0df8d8abe19c8af6ded6d8fd23216d1f767bec1

It could solved by one line code in the last section of that commit.

I saw a lot delegate and protocol, I think it's over designed. If I want do the style update, I can simply do a super class or extension. Or just do it in Container, such as NavigationViewController. So All the ViewControllers will response to style change. And I prefer to use notifications for this task.
