### ISSUE TITLE
feat: implement Page Lists and Landmarks

### ISSUE THREAD

**Issue by llemeurfr** [readium/r2-testapp-swift#31]
Page Lists and Landmarks are an important feature of a Reading System, for higher education. 

The UI needs first to be discussed (common to iOS and Android).

**Comment by HadrienGardeur** [comment]
This should already be handled by the streamer and the model, which means that the only missing part is the UI.

I would tie the page list and landmarks to the table of contents.

**Comment by aferditamuriqi** [comment]
implemented here https://github.com/readium/r2-testapp-swift/pull/249
