### ISSUE TITLE
Should we raise the minimum supported iOS version to iOS 10?

### ISSUE THREAD

**Issue by mickael-menu** [readium/r2-testapp-swift#329]
EDIT:
[We talked about this issue on the last dev meeting](https://docs.google.com/document/d/1hP3l7mY4T-Rg7emw2qPnT7e3bpN3y3Uxcm4qaobrvLw/edit?usp=sharing), and agreed on dropping support for iOS 9. Unfortunately, we don't have the resources to maintain the toolkit on such older versions. Apple is not making it easy.

**The next tagged release will be the last one supporting iOS 9.**

---
I'm testing the waters.

Right now, Readium supports down to iOS 9, but:
* the PDF navigator requires iOS 11
* the audiobook navigator will require iOS 10

Personally, I think it's time to raise the minimum requirement to iOS 10. 

3.3% of iPads are < iOS 10, and only 0.1% on iPhones.
https://david-smith.org/iosversionstats/

Any disagreement?

**Comment by llemeurfr** [comment]
We'll lose iPad 2 and 3, iPad Mini, iPhone 4S (from this [source](https://story.backmarket.fr/quel-ios-pour-quel-ipad-la-liste-des-compatibilites/4914/)).

I'm not against, but will it be possible for a developer to create an EPUB only reading app with Readium Mobile, or will iOS 10-only API be spread everywhere in the code?

**Comment by aferditamuriqi** [comment]
I actually thought we already had raised it to 10. I’ll be in favor of 10. I believe LCP lib requires 10 as well. (I can double check that )

**Comment by HadrienGardeur** [comment]
At this point in time, I think it's hard for us to promise support for iOS 9. 

I'm also in favor of 10+. 

Most devices updated to 10 now support up to iOS 12. It's only with iOS 13 that a number of devices got left behind by Apple.

**Comment by mickael-menu** [comment]
> I'm not against, but will it be possible for a developer to create an EPUB only reading app with Readium Mobile, or will iOS 10-only API be spread everywhere in the code?

No, they will have to stay with the last compatible version of Readium. But honestly my guess is that most if not all apps using Readium are at least already on iOS 10 or 11. Apple is pretty aggressive in encouraging developers to only support the last 2 versions of iOS. For example, iOS 9 is not supported anymore by Xcode 11.

**Comment by mickael-menu** [comment]
I just want to add that there's no real need to upgrade to iOS 10 right now. We can limit new APIs to iOS 10+ like I did with PDF and audiobook navigators.

However, this prevents us from using more modern APIs and adds to the maintenance load. For example, ES6 is not supported by iOS 9, so we can't use it in HTML navigator's JavaScripts. And like I said, I'm pretty sure that the vast majority of Readium developers are not targeting iOS 9 anyway.

**Comment by ettore** [comment]
NYPL is still targeting iOS 9.3 as deployment target and has a need to continue to do so. So this would be a problem for us unfortunately.

**Comment by mickael-menu** [comment]
@ettore 

> NYPL is still targeting iOS 9.3 as deployment target and has a need to continue to do so. So this would be a problem for us unfortunately.

Alright, I guess we could stick with iOS 9 for now and revisit this issue in a year or so. Let us know if your requirements change until then.

Do you have more information about the reason why you're targeting iOS 9? Is it to make sure that you leave no devices behind?

**Comment by aferditamuriqi** [comment]
I am quite sure that we had this conversation before on an engineering call, and we had decided to move on to 10. I can check what the issue was with LCP that it needed to be 10. it's been at least 6 months ago.

**Comment by aferditamuriqi** [comment]
> We'll lose iPad 2 and 3, iPad Mini, iPhone 4S (from this [source](https://story.backmarket.fr/quel-ios-pour-quel-ipad-la-liste-des-compatibilites/4914/)).
> 
> I'm not against, but will it be possible for a developer to create an EPUB only reading app with Readium Mobile, or will iOS 10-only API be spread everywhere in the code?

we would lose those most likely anyway, since those are 32-bit device, as far as I can tell 

anyone that uses the modules as submodules and not as Carthage or pod dependency, could set their own minimum version. we just need to make sure that features not available in 9 are flagged properly, even if we raise the minimum to 10. 

at some point we had decided to stay within the supported version of what apple does anyway if apple discontinues a version, we do too. It will be difficult to make everyone happy, but even more difficult to have workaround based on available features in newer versions.

**Comment by ettore** [comment]
> Do you have more information about the reason why you're targeting iOS 9? 

We still have significant usage on iOS 9.3.

**Comment by mickael-menu** [comment]
> We still have significant usage on iOS 9.3.

Okay so it's not a hard requirement. I'm quite surprised you still have a significant usage since 9.3 is around 1.5% worldwide. Are you sourcing these stats from your app usage over the last few months?

Personally I would be fine staying at 9.3 for a few more months (maybe until iOS 14?) if:

* we don't offer support pre iOS 10
* new features can use iOS 10+ APIs

Or until there's something fundamental popping up which would benefit from iOS 10+.

> I am quite sure that we had this conversation before on an engineering call, and we had decided to move on to 10.

Yeah it rings a bell.

**Comment by llemeurfr** [comment]
Could we create a specific "iOS9" branch which only processes EPUB (with LCP if we conclude that LCP does not use iOS 10 features; but no audiobooks) and would stay frozen? (but could be maintained if some bad bug appears, something impossible with a github tag)
Developers willing to target iOS9 in the future (i.e. create a simple app for old devices) could refer to this branch. Even if the architecture evolves, developers could still find a ready to use sdk there. 
Later, we would do the same for iOS 12 maybe, with audiobook support this time, and so on. 
This would free us from maintaining a large set of targets in the codebase.

**Comment by aferditamuriqi** [comment]
I am not really in favor of those kind of branches , if we say we keep a version of the sdk to iOS 9, then a tag / release would be best for this . Since there won’t be any evolution to the code after that .

**Comment by llemeurfr** [comment]
> Since there won’t be any evolution to the code after that .

This is the crux of the issue. As I said with a branch it "could be maintained if some bad bug appears, something impossible with a github tag".

**Comment by mickael-menu** [comment]
> Could we create a specific "iOS9" branch which only processes EPUB (with LCP if we conclude that LCP does not use iOS 10 features; but no audiobooks) and would stay frozen? (but could be maintained if some bad bug appears, something impossible with a github tag)

Yes I think that could work. Alternatively (maybe cleaner), we could still use GitHub tags by reserving the third number of the version number for iOS 9 bug fixes (e.g. 1.2.**x**).

However, like Aferdita said, I think we should still only support what Apple is supporting. I personally have no way to run the project on iOS 9. But contributors could provide bug fixes which could be released as a new minor version.

Whatever we decide, I think we should wait for the public API to stabilize before freezing iOS 9 codebase, since it would make upgrading less painful. This should take a few more months.

**Comment by mickael-menu** [comment]
@ettore [We talked about this issue on the last dev meeting](https://docs.google.com/document/d/1hP3l7mY4T-Rg7emw2qPnT7e3bpN3y3Uxcm4qaobrvLw/edit?usp=sharing), and agreed on dropping support for iOS 9. Unfortunately, we don't have the resources to maintain the toolkit on such older versions. Apple is not making it easy.

**The next tagged release will be the last one supporting iOS 9.**

I'm keeping this issue opened until support is actually dropped.

**Comment by mickael-menu** [comment]
iOS 10 is now the minimum required version.

The last tagged version still supporting iOS 9 is `2.0.0-beta.1` ([see this issue](https://github.com/readium/r2-testapp-swift/issues/351) for Xcode 12 troubleshooting with `2.0.0-beta.1`)
