### ISSUE TITLE
I push project to test fight. issues ITMS-90809: Deprecated API Usage

### ISSUE THREAD

**Issue by Supalet** [readium/r2-testapp-swift#334]
my CartFile 
github "omise/omise-ios" ~> 3.0
github "tadija/AEXML" == 4.2.2
github "onevcat/Kingfisher" == 5.9.0
github "weichsel/ZIPFoundation" == 0.9.9
github "jdg/MBProgressHUD" == 1.1.0
github "stephencelis/SQLite.swift" == 0.12.2
github "edrlab/GCDWebServer" == 3.6.2
github "krzyzanowskim/CryptoSwift" == 1.2.0
github "cezheng/Fuzi" == 3.1.1
github "dexman/Minizip" == 1.4.0
github "readium/r2-shared-swift" == 1.4.3
github "readium/r2-streamer-swift" == 1.2.5
github "readium/r2-navigator-swift" == 1.2.6
github "readium/readium-opds-swift" == 1.2.3
github "mxcl/PromiseKit" ~> 6.8
github "scinfu/SwiftSoup" == 2.3.1

I searched in my project.Found there have UIWebview in Library.
<img width="1492" alt="Screen Shot 2563-05-12 at 11 57 46" src="https://user-images.githubusercontent.com/65211118/81641731-e560b600-944b-11ea-924e-4c02cbab01c8.png">

**Comment by mickael-menu** [comment]
Hi,

We pushed a few betas ourselves recently but didn't get this warning.

Looking at your logs, I guess you used grep to find the occurrences of `UIWebView`? The problem is that this won't find actual usages but any mention.

Can you try again with this command from your project's folder?

```
find . -exec nm -A {} \; 2> /dev/null | grep "UIWebView"
```

This might take a few minutes to complete.

**Comment by mooka-ventures** [comment]
FYI - We pushed our app to TestFlight and we don't see this "Deprecated API Usage' warning.

**Comment by mickael-menu** [comment]
@mooka-ventures Thanks for sharing your experience 👍 

I'll close this one for a lack of activity.
