### ISSUE TITLE
Several issues after CSS update to the latest alpha

### ISSUE THREAD

**Issue by aferditamuriqi** [readium/r2-testapp-swift#34]
• background and foreground of text not changing when changing the mode to sepia or night
• publisher default seems to not have any effect anymore 
• font change is not being applied 
• advanced settings not working except the page margins

some more info:
Before updating to the latest alpha, all we had was the following 3 css files which didn't contain any reference to other css files. 

[ReadiumCSS-before](https://github.com/readium/r2-streamer-swift/blob/master/R2Streamer/ReadiumCSS-before.css)
[ReadiumCSS-after](https://github.com/readium/r2-streamer-swift/blob/master/R2Streamer/ReadiumCSS-after.css)
[ReadiumCSS-default](https://github.com/readium/r2-streamer-swift/blob/master/R2Streamer/ReadiumCSS-default.css)

we need to review the implementation and fix what might be missing, as it seem like several of the css files under modules are not being used.

**Comment by JayPanoz** [comment]
Hmmm that’s strange, I’ve just re-re-run a comparison between the old and the new ones and there shouldn't be any breaking change – when upgrading to alpha, the iOS implementation even served as a reference for all implementations. 

So I run validation for the new ones and it seems everything should be OK, there is no error reported. 

> Before updating to the latest alpha, all we had was the following 3 css files **which didn't contain any reference to other css files.**

Emphasis mine as this detail is kinda strange to me. There shouldn’t be any reference to other css files in the production-ready stylesheets (those who list other css files with `@import` in the `src` folder are indeed meant to be compiled first).

Are you using the ones in the `dist` folder, [to be found here](https://github.com/readium/readium-css/tree/develop/css/dist). This indeed is the output when compiling those stylesheets using `npm run build`.

**Comment by aferditamuriqi** [comment]
@JayPanoz thank you for your help, all makes sense of course, i have to admit i misased the compiling part . so i am closing this issue.
