### ISSUE TITLE
Save last page read

### ISSUE THREAD

**Issue by ghost** [readium/r2-testapp-swift#340]
Is there documentation on how to save last page read ? I believe we saw this feature on the Android library but didn't find it in the example app. 

So can someone please point me to the documentation/code on how to save last page read ?
An example code would be good too.

**Comment by mickael-menu** [comment]
Is your question about Android or iOS? Because you posted it on the Swift test app

**Comment by mooka-ventures** [comment]
@mickael-menu this question is for iOS. Right now we want to know how to save last page read on iOS.

**Comment by mickael-menu** [comment]
We are using a model called [`Locator`](https://github.com/readium/architecture/tree/master/models/locators/) to represent a location in a publication. It is serializable as JSON and can be used to persist and restore the last page read.

On iOS, you can observe the current locator when the location changes with `NavigatorDelegate.navigator(_:locationDidChange:)`:

https://github.com/readium/r2-testapp-swift/blob/c600cfc669db56328532958f5334060ee1e718be/r2-testapp-swift/Reader/Common/ReaderViewController.swift#L249-L265

To restore the locator when opening the publication again, you can give it to the `initialLocation` parameter of the navigator view controller:

https://github.com/readium/r2-testapp-swift/blob/c600cfc669db56328532958f5334060ee1e718be/r2-testapp-swift/Reader/EPUB/EPUBViewController.swift#L23

**Comment by mooka-ventures** [comment]
thanks @mickael-menu . Will try that, will try to add a PR for documentation in case we get this working.
