### ISSUE TITLE
Is the Highlight & Note feature supported?

### ISSUE THREAD

**Issue by mooka-ventures** [readium/r2-testapp-swift#342]
* Checked the iOS demo app and we don't see the "Highlight" and "Note" feature. 
* Right now we see these three "Copy, Lookup, Share" options when we highlight any text.
![highlight-note-missing-feature](https://user-images.githubusercontent.com/22156064/87582940-07ff8d00-c690-11ea-9a11-21727cbfe32c.jpg)

* Do we have some documentation on how to add "Highlight" and "Note" features to the iOS reader ? 
Are those features already available? But are not part of the test iOS Swift app ? 
Could someone point out the way to enable these two features (Highlight, Note) in the iOS Readium reader ?

**Comment by mickael-menu** [comment]
Right now highlights are not yet implemented on the Swift toolkit. But we plan to add this feature soon this year.
