### ISSUE TITLE
How to hide Copy & Share options

### ISSUE THREAD

**Issue by ghost** [readium/r2-testapp-swift#343]
How can we hide Copy and Share options when a text is selected in an epub file.

**Comment by mickael-menu** [comment]
When creating an `EPUBNavigatorViewController`, you can provide an instance of `EPUBNavigatorViewController.Configuration`. The `editingActions` are used to set up which options appear in the selection menu.

```swift
let navigator = EPUBNavigatorViewController(
    ...,
    config: .init(
        editingActions: []
    )
) 
```

**Comment by mooka-ventures** [comment]
We tried this, but "Share" still shows up.

**Comment by mickael-menu** [comment]
Okay, then I'll have to take a look. Can you tell me which versions of Readium, Xcode and iOS you're using?

**Comment by mooka-ventures** [comment]
Thanks..Readium we used the one from the test app readme setup instructions..Xcode is latest 11.5 and iOS we are testing on the simulator iPhone SE (2nd Feb)

**Comment by mickael-menu** [comment]
I probably won't have time to look at this for weeks unfortunately. If it's a blocking issue for you, please consider contributing a pull request.

It's supposed to work in `WebView.swift` by checking in `canPerformAction()` that the `action` is part of the `EditingAction` enum.  For `share`, it's checking `shareSelection:`, but maybe the name of the selector changed in the latest iOS version.

**Comment by mickael-menu** [comment]
I did a quick inspection, it looks like since iOS 13 the way we handle masking "Look Up" and "Share" doesn't work anymore.

There's the same issue on the PDF navigator, and here's a lead to fix this: https://stackoverflow.com/a/61361294/1474476

**Comment by rocxteady** [comment]
I made a PR for this issue. -> https://github.com/readium/r2-navigator-swift/pull/149
Can you check when you are avaiable? @mickael-menu
