### ISSUE TITLE
GCDWebserver crash on integrating Readium library

### ISSUE THREAD

**Issue by mooka-ventures** [readium/r2-testapp-swift#346]
Error seen:
![gcdwebserver_crash](https://user-images.githubusercontent.com/22156064/88080734-4edbff80-cb34-11ea-9aa4-74aa9314d85b.jpg)

These are the dependencies being installed during the integration process.
```
Installing CryptoSwift (1.3.1)
Installing Fuzi (3.1.2)
Installing GCDWebServer (3.5.4)
Installing Minizip (1.0.0)
Installing R2Navigator (1.2.7)
Installing R2Shared (1.4.5)
Installing R2Streamer (1.2.6)
Installing ReadiumOPDS (1.2.4)
Installing SwiftSoup (2.3.2)
```

It might be because the r2 streamer uses custom GCDWebserver from EDRLab which is 3.6.2 but here we are seeing GCDWebServer (3.5.4) being installed. Is that the issue ? if so could you please suggest how to resolve this issue ?

Any suggestions ?

**Comment by mickael-menu** [comment]
It looks like you have a number of issues integrating with CocoaPods. We usually have more success with Carthage, would you consider using it instead?

How does your `Podfile` look like?

**Comment by mooka-ventures** [comment]
Thanks @mickael-menu , as per suggestion we switched to Carthage and it works fine. Also the GCDWebserver used is `github "edrlab/GCDWebServer" == 3.6.2`.
