### ISSUE TITLE
Can't submit to App Store Connect: Invalid font GCDWebUploader.bundle/fonts/glyphicons-halflings-regular.woff

### ISSUE THREAD

**Issue by mickael-menu** [readium/r2-testapp-swift#350]
Since last week, we were not able to submit any new build for review to the App Store Connect (sending to TestFlight is fine). 
It seems that [recently Apple changed something](https://developer.apple.com/forums/thread/657598) in their validation process.

> **ITMS-90792**: Invalid font - There was an error validating the font at '[...]/Frameworks/GCDWebServer.framework/GCDWebUploader.bundle/fonts/glyphicons-halflings-regular.woff'. Validation failed.
> **ITMS-90792**: Invalid font - There was an error validating the font at '[...]/Frameworks/GCDWebServer.framework/GCDWebUploader.bundle/Contents/Resources/fonts/glyphicons-halflings-regular.woff'. Validation failed.

Looking at GCDWebServer, these fonts are probably not useful for Readium. So we might be able to remove them from [EDRLab's fork](https://github.com/edrlab/GCDWebServer) (cc @aferditamuriqi)

I opened a [twin issue on the official repo](https://github.com/swisspol/GCDWebServer/issues/501).

**Comment by mickael-menu** [comment]
@aferditamuriqi Any news regarding removing these fonts from GCDWebServer?

**Comment by aferditamuriqi** [comment]
@mickael-menu i can't access or create a PR to edrlab fork on this, but i referenced my fork where i removed the fonts

**Comment by mickael-menu** [comment]
Okay thanks, I'll see what we can do with Laurent.

**Comment by aferditamuriqi** [comment]
Fixed in https://github.com/edrlab/GCDWebServer/releases/tag/3.6.3

**Comment by mickael-menu** [comment]
Thanks @aferditamuriqi
