### ISSUE TITLE
Issue building with Carthage on Xcode 12

### ISSUE THREAD

**Issue by mickael-menu** [readium/r2-testapp-swift#351]
[There's currently an issue with Xcode 12 when trying to build Carthage dependencies](https://github.com/Carthage/Carthage/issues/3019). Unfortunately, it's not something we can address in Readium.

If you don't want to stick with Xcode 11, a workaround until Carthage is fixed is to use [the following script](https://github.com/Carthage/Carthage/issues/3019#issuecomment-665136323) instead of the regular Carthage command:

```sh
#!/usr/bin/env bash

# carthage.sh
# Usage example: ./carthage.sh build --platform iOS

set -euo pipefail

xcconfig=$(mktemp /tmp/static.xcconfig.XXXXXX)
trap 'rm -f "$xcconfig"' INT TERM HUP EXIT

# For Xcode 12 make sure EXCLUDED_ARCHS is set to arm architectures otherwise
# the build will fail on lipo due to duplicate architectures.
echo 'EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200 = arm64 arm64e armv7 armv7s armv6 armv8' >> $xcconfig
echo 'EXCLUDED_ARCHS = $(inherited) $(EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_$(EFFECTIVE_PLATFORM_SUFFIX)__NATIVE_ARCH_64_BIT_$(NATIVE_ARCH_64_BIT)__XCODE_$(XCODE_VERSION_MAJOR))' >> $xcconfig

export XCODE_XCCONFIG_FILE="$xcconfig"
carthage "$@"
```

Add it to `/usr/local/bin`, `chmod a+x carthage.sh` and then you can use it like that: `carthage.sh update --platform ios`.

**Comment by mickael-menu** [comment]
This is fixed in Carthage 0.37, by using `--use-xcframework`

```
carthage update --use-xcframeworks --platform ios
```

**Comment by mickael-menu** [comment]
Looks like it failed with:

```
r2-shared-swift/Toolkit/XML/Fuzi.swift:13:8: error: module 'Fuzi' was created for incompatible target arm64-apple-ios8.0: .../r2-testapp-swift/Carthage/Checkouts/r2-shared-swift/Carthage/Build/iOS/Fuzi.framework/Modules/Fuzi.swiftmodule/arm64.swiftmodule
import Fuzi
```

[It might have something to do with `VALID_ARCHS`](https://github.com/SwiftyJSON/SwiftyJSON/issues/1081) but until we figure it out, the previous script still work. 

(cc @aferditamuriqi What command did you use exactly to build the Carthage dependencies, and does it work in `r2-testapp-swift` for you?)

**Comment by mickael-menu** [comment]
I can build sucessfully with `--use-xcframeworks` and Xcode 12 with the changes introduced in this PR: https://github.com/readium/r2-testapp-swift/pull/363

**Comment by mrifni** [comment]
I have successfully built the latest develop branch project with xcode version `Version 12.4 (12D4e)`

**Comment by mickael-menu** [comment]
Xcode 12 chronicles, part II 😓 

As stated in this issue, since Xcode 12 we must build XCFrameworks with Carthage.

Unfortunately, **Carthage failed if we were still linking to regular frameworks in R2 modules** (let's call it the 🍌  issue). The solution was to switch to XCFrameworks for every nested dependencies.

However, a XCFramework is resolved with a path relative to the local project, while a regular `.framework` is resolved implicitly in the whole workspace. This meant that when integrating R2 modules as git submodules, there were some potential conflicts between the XCFramework dependencies referenced in each R2 module, which were sourced from each module's `Carthage/Build` folder.

Somehow, Xcode 12 didn't mind until 12.5, which now complains with the following errors (**only when integrating R2 as git submodules**):

<img width="1439" alt="Screenshot 2021-04-28 at 12 37 57" src="https://user-images.githubusercontent.com/58686775/116559113-61276d00-a900-11eb-844a-59962ddd561e.png">


The solution seems to revert back to linking to regular `.framework`s in R2 modules to let Xcode resolve dependencies implicitly in the workspace. But, remember the 🍌 issue we had with Carthage. [Turns out this was a bug in Carthage 0.37, which should be fixed in the upcoming Carthage 0.38](https://github.com/Carthage/Carthage/issues/3122).

Until then, a workaround is to make sure that the `Carthage/Build/iOS` folder exists before running the `carthage update --use-xcframeworks --platform ios` command.

**Comment by alexwhb** [comment]
@mickael-menu That saved me hours of research as to what's going on. Thanks for posting.

**Comment by mickael-menu** [comment]
[Carthage 0.38.0](https://github.com/Carthage/Carthage/releases/tag/0.38.0) is out:

> Fixed building XCFrameworks with nested dependencies no longer requires a platform-specific Build directory (i.e. Carthage/Build/iOS) to exist (#3135).

@aferditamuriqi They also wrote something that might be interesting for R2LCPClient:

> Prebuilt dependencies (for binary only frameworks and GitHub release assets) may use XCFrameworks, which are checked for compatibility and extracted into the Build folder (#3123). See the section below on compatibility information for framework authors.

**Comment by mickael-menu** [comment]
I reverted back to using the `xcframework` paths in the Xcode project, instead of the `framework` ones, because:

* Before Xcode 12.5, the build failed and some of our contributors can't upgrade Xcode.
* The Carthage CI failed (https://github.com/readium/r2-testapp-swift/pull/394) for the same reason.
* Now we can use SPM for Git submodules. 

See https://github.com/readium/r2-shared-swift/pull/153

That means that using Readium as Git submodules with Carthage is not possible anymore with Xcode 12.5+. If you were doing this, you can either:

* Use Swift Package Manager (recommended).
* Generate the project using `xcframework` in your forks.

@alexwhb Let me know if you have an issue with this.

**Comment by alexwhb** [comment]
@mickael-menu This is actually fantastic news. I'm using SwiftPM in most of my project other than a few a few modules including this one that up till now did not have a way to use them with SwiftPM. I'll give it a try soon. 👍 Thanks for letting me know.
