### ISSUE TITLE
Some questions, I want to make an Epub reader based on Flutter

### ISSUE THREAD

**Issue by 312654929** [readium/r2-testapp-swift#358]
Hello, to be honest, I haven't been working on mobile apps for a long time. I want to take some ideas from this project to the Flutter app. Now ,i have the following problems:
1. I found that the bar effect worked when I applied Readium Css (turning the page horizontally), but the font size became very small and some books also had two bars under the phone size screen. I tried to change the font-size: 100% property and found that the spacing was not very symmetric.
2. I don't know how to modify the long-pressed selected text in flutter
I would appreciate it if you could reply!!

**Comment by 312654929** [comment]
## haha

**Comment by mickael-menu** [comment]
We don't have much experience integrating the Readium Toolkit with Flutter. I think some used React Native though.

Also I don't fully understand your questions, could you detail and add maybe some screenshots/screencasts?
