### ISSUE TITLE
Error running carthage update --use-xcframeworks

### ISSUE THREAD

**Issue by Dennis19872020** [readium/r2-testapp-swift#374]
run carthage update --use-xcframeworks --platform iOS error

**Comment by mickael-menu** [comment]
Please share:

* The content of your `Cartfile`
* How your project is organized (submodules or Carthage dependencies)
* In which folder did you run `carthage update --use-xcframeworks --platform iOS`
* The output of `carthage update --use-xcframeworks --platform iOS`
* The output of `ls r2-testapp-swift/Carthage/Build`

**Comment by mickael-menu** [comment]
Closing from lack of activity.
