### ISSUE TITLE
framework Missing completely

### ISSUE THREAD

**Issue by KohiOnCode** [readium/r2-testapp-swift#388]
@HadrienGardeur @ettore @danielweck @NikitaEvidentPoint @iaomw Please check & reply as soon as possible.

![Screenshot 2021-06-03 at 5 24 45 PM](https://user-images.githubusercontent.com/85291713/120640872-9b040a00-c490-11eb-9623-4f75b03797cf.png)

https://github.com/readium/r2-testapp-swift.git

when I downloaded the testApp then it shows missing frameworks.

**Comment by mickael-menu** [comment]
It doesn't matter, it's a side-effect of displaying several means of integration. Check out instructions on https://github.com/readium/r2-workspace-swift
