### ISSUE TITLE
Wrong content displayed after showing TOC on iPhone

### ISSUE THREAD

**Issue by ettore** [readium/r2-testapp-swift#393]
### What happened?

After opening and closing the Table of Contents, the page displayed is not the same that was displayed before.

https://user-images.githubusercontent.com/289104/123177997-30b10a80-d43b-11eb-9dd6-ed71472319a2.mov

### Expected behavior

The content displayed should not change after opening and closing the TOC.

### How to reproduce?

1. build the test app from `r2-testapp-swift` repo, using the latest code from `develop` for all repos. I used the carthage target, although I created a workspace with the repos individually checked out, as suggested in the README.
2. Launch the app in an iPhone simulator, e.g. iPhone 12.
3. tap on Moby Dick -- any other default books in the test app also fine, except the graphic novel.
4. browse to a page that is not the beginning of a chapter
5. open the TOC
6. note how in the background (beneath the sliding up pane) the content appear to change
7. hit Cancel
8. The content now displayed is different. Often times it's one page earlier, some other times it's a completely different location in the book (see screencast, where it jumped from the 2nd page of chapter 14 to the beginning of chapter 12)

#### Readium versions

* `r2-shared-swift`: develop f813f860f48fe97cd30c8fe25f8405e65ac7cf91
* `r2-streamer-swift`: develop 6fea51c6598904f663883dfadae2a696f377c51a
* `r2-navigator-swift`: develop 99cd5f26772fa1995f4d45151bb98dc42a4a4df0
* `r2-opds-swift`: develop 919880add21321dafe88b39600fb43e0ab0ff231
* `r2-testapp-swift`: develop b2db3fd83d14064eedf781074cfd2cf56bfddaa1

The 2.0.0 (2.0.1 on `shared`) tags also shows this bug.

#### Development environment
```
$ echo "macOS: `sw_vers -productVersion`"
macOS: 10.15.7

$ echo "platform: `uname -m`"
platform: x86_64

$ echo "carthage: `carthage version`"
carthage: 0.38.0

$ xcodebuild -version
Xcode 12.4
Build version 12D4e
```

#### Testing device

* iOS version: 14.4
* Model: iPhone 12
* Is it an emulator? Yes

### Additional context

* Are you willing to fix the problem and contribute a pull request? 
Yes, but I will need some guidance. Not familiar at all with the view hierarchy/gesture recognizers/spreads are organized in these projects.

When I hit the TOC button in the nav bar, the [`EPUBSpreadView::didTapBackground(_:)`](https://github.com/readium/r2-navigator-swift/blob/99cd5f26772fa1995f4d45151bb98dc42a4a4df0/r2-navigator-swift/EPUB/EPUBSpreadView.swift#L213) gesture recognizer callback is triggered. This alone seems wrong to me. After that this reaches [`ReaderViewController::navigator(_:didTapAt:)`](https://github.com/readium/r2-testapp-swift/blob/eb1d70b377cc577b567c067f25b5de0128d7a85a/r2-testapp-swift/Reader/Common/ReaderViewController.swift#L335) and since the `point` variable is (x=0, y=845), this is interpreted as a "go Left" action.

**Comment by mickael-menu** [comment]
Thanks for the detailed bug report 👍 

Unfortunately I was not able to reproduce this with the same simulator and `develop` branches.

I'm using the latest Xcode 12.5.1, although I can't see how that would be the issue. `EPUBSpreadView::didTapBackground(_:)` is not called in my case either, but maybe that would be the root cause of the issue you're seeing. Did you manage to reproduce this from a real device? And do you have the problem in your own apps?

https://user-images.githubusercontent.com/58686775/123408410-46464180-d5ad-11eb-8476-c775806c87bb.mov

**Comment by ettore** [comment]
I can't really explain it, but after rebuilding the app toggling between the 2.0.0 versions and `develop`, I can no longer reproduce this problem. I did wipe DerivedData and various carthage folders, so maybe that was it. But I doubt it, because it would have been either 2.0.0 code OR `develop` code, and now I can no longer see it even when I use 2.0.0 code. `EPUBSpreadView::didTapBackground(_:)` is no longer being called (correctly so)

I was able to see the issue on a physical device too (iPhone 6 / iOS 12.5.3). 

However, I do see [this issue in our app](https://jira.nypl.org/browse/IOS-219) (simulated and physically on iPhone 11 / iOS 14.6), but only for some books, and only on iPhone. We show the TOC in a pushed VC (instead of modally) but the effect is the same: there's a tap being detected when tapping on the TOC button, and after the reader view reappears, the content displayed can be vastly different.

At this point I'd like to run a few more tests next week before closing this issue, since it's no longer happening and I can't really explain why.

**Comment by ettore** [comment]
I'm going to close this since I can no longer reproduce this on the testapp, plus I haven't had (and likely won't have) the time to investigate this further on either end (NYPL or R2 code).

I wonder now if this was the result of a bad build (related to what I'm fixing with PRs such as https://github.com/readium/r2-shared-swift/pull/153 )...
