### ISSUE TITLE
EPUB TestSuite module 120 causes app to crash

### ISSUE THREAD

**Issue by rkwright** [readium/r2-testapp-swift#4]
The EPUB TestSuite 120 (Media Overlays) causes the application to crash, even before it displays the library or tries to open the EPUB.

Method:

1. Start the app
2. Add the [module 120](http://epubtest.org/epubs/epub30-test-0120-20160116.epub) to the library
3. Try to start the app

Result:  Crashes every time. No message, nothing.

Tried deleting the app and adding the module alone.  Same result.  Other modules in EPUB TestSuite seem to work (only have tried first 5 so far).

Test App: 0.2 (2)  (installed from preflight)
Device: iPad 5
OS: iOS 11.0.3
Memory: 16 GB

**Comment by HadrienGardeur** [comment]
I have a slightly related question for you @rkwright: is there an OPDS feed with all those titles?

I think @danielweck mentioned this before.

**Comment by rkwright** [comment]
@HadrienGardeur Not as far as I know.  The only books in the library were the books the app installs by default.  I don't think they are OPDS feeds.

**Comment by danielweck** [comment]
Do you mean this?
https://readium.firebaseapp.com/?epubs=epub_content%2Fepub_testsuite.opds

Direct OPDS link:
https://readium.firebaseapp.com/epub_content/epub_testsuite.opds

**Comment by HadrienGardeur** [comment]
@danielweck yeah that's exactly what I had in mind.

Hopefully we'll be able to embed this feed in the test app soon enough.

**Comment by rkwright** [comment]
Loading the fixed-layout media-overlay test suite ([220](http://epubtest.org/epubs/epub30-test-0220-20160116.epub)) DOESN'T cause a crash.  It doesn't work because media overlays are not supported, but it doesn't crash.

**Comment by iaomw** [comment]
Hey, guys. I am not sure what are you talking about. Feels complex from your discussion. But when I was try to debug it, it's much easier and obvious. 

There is a bad bad use of Swift language, somebody didn't do the null check. 
```
let audioFilePath = parse(audioElement: audioElement)
newNode.audio = normalize(base: base!, href: audioFilePath!)

```
And there is a corner case didn't covered when parsing the logic of audio information.
`static fileprivate func parse(audioElement: AEXMLElement) -> String?`

You see, there is no "clipBegin" in that "xml" element. 
Maybe it's valid, or maybe the book creator didn't follow some guideline.
"\t\t\t\t<audio src=\"../audio/clip_times_tests1A.mp3\" clipEnd=\"00:00:04.650\" />"

**Comment by iaomw** [comment]
Should `SMILParser` support both `SML 3.0` and `SML 1.0`?

**Comment by iaomw** [comment]
In the current code, it will ignore any `audio` element which doesn't have both `clipBegin` and `clipEnd`. That's logically wrong. Is that a discussed result or a mistake?

https://www.w3.org/TR/smil/smil-extended-media-object.html#adef-clipEnd

In the documents, both `clipBegin` and `clipEnd` are optional, it's totally valid. The current code base will also calculate the `duration` based on `clipBegin` and `clipEnd`. But that's logically impossible to calculate `duration` if `clipEnd` is missing.  In that case, the only solution for `duration` is read the audio file directly for this metadata. 

That might be the reason why it was given up. 

What is the use case of that `duration`? I didn't see any code using it. 
Does it required to get `duration` values once for all before open the book? 
Is that OK to prepare the `duration` on the fly just before play the specific audio?

**Comment by danielweck** [comment]
The SMIL parser should certainly handle missing `clipBegin` and `clipEnd` attributes.
The SMIL playback engine should be capable of handling:
* missing `clipBegin`: equivalent to "beginning of audio file" (`0`)
* missing `clipEnd`: equivalent to "end of audio file" (which can ; for example ; be statically encoded as `-1`, and resolved at runtime by waiting for the "end of audio stream" event)

Strictly-speaking a "duration" property is not needed for the playback engine to function properly. However "duration"-related metadata in Media Overlays (expressed in EPUB `package.opf`) can be useful to implement a UX that allows for arbitrary / random seeking inside a start-end linear timeline (see for example the Readium1 Chrome app / cloud reader UI).

**Comment by danielweck** [comment]
For your information, the Readium(1) cloud reader exposes an OPDS feed for the *expanded* epub-testsuite EPUBs located in the IDPF GitHub repository:

https://readium.firebaseapp.com/?epubs=epub_content%2Fepub_testsuite.opds

For example test number `120`:

http://epubtest.org/epubs/epub30-test-0120-20160116.epub
=>
https://github.com/IDPF/epub-testsuite/tree/master/content/30/epub30-test-0120
