### ISSUE TITLE
Need visual indicator for downloading and loading book. 

### ISSUE THREAD

**Issue by iaomw** [readium/r2-testapp-swift#40]
It will become an issue for slow internet and big book. Looks and feels strange.

Also consider accessibility features, such as a little announcement.

**Comment by llemeurfr** [comment]
We'll first suppress the pop-up when we side-load a publication and replace it with a spinner in the status bar. 
We will, if time allows, also add a temporary blank (or blue) cover image at place where the publication will appear. Which means that the sort order for publications will be the date of import in the catalog (side-loading or from an OPDS catalog). Later we'll add a choice for sorting order in the catalog.

**Comment by llemeurfr** [comment]
We can use https://github.com/jdg/MBProgressHUD as a ready to use component.
