### ISSUE TITLE
I want to disable select and copy popup

### ISSUE THREAD

**Issue by ktech643** [readium/r2-testapp-swift#405]
I am using r2 for Epub reader I want to disable selection for text and the popup appeared in image
![Image 2021-10-06 at 3 52 08 AM](https://user-images.githubusercontent.com/68194292/136193426-c00b9555-25f7-45f6-9f8e-a06da7a94f7a.jpeg)
.

**Comment by mickael-menu** [comment]
You can't disable text selection.

However you can disable the Copy by removing the `EditingAction.copy` item (and `.share` from the `editingActions` parameter of the EPUB navigator config object).

```swift
let config = EPUBNavigatorViewController.Configuration(
    editingActions: [.lookup]
)
let navigator = EPUBNavigatorViewController(
    publication: publication, 
    initialLocation: book.progressionLocator, 
    resourcesServer: resourcesServer,
    config: config
)
```
