### ISSUE TITLE
Adjust number of books shown in the Collection View

### ISSUE THREAD

**Issue by aferditamuriqi** [readium/r2-testapp-swift#43]
Currently no matter the device we show just 3 books in a row. which is not ideal for larger screens like iPads

**Comment by HadrienGardeur** [comment]
We're currently working on this for Aldiko and decided to use 4 in portrait and 5 in landscape on the iPad.

**Comment by HadrienGardeur** [comment]
I don't own an iPad Pro, so I haven't tried it device in hands yet (which IMO is the only good way to test this out).

On a normal iPad, it looks really quite good. We had 3 covers in portrait before and I really didn't liked it much.

I wouldn't do dynamic scaling based on the size of the covers, I find this confusing from a UX perspective. Ideally this would be entirely adaptive, but once you reach a certain number of items per row, it's better to add whitespace than more content (this will be extremely important on desktop and Chrome OS).

**Comment by aferditamuriqi** [comment]
ok, that makes sense, I will test it on my iPad Pro and see how it would look with 4 and 5, once we have this update, but it shouldn't be an issue distinguishing between phone, iPad and iPad Pro if needed.

**Comment by aferditamuriqi** [comment]
I am closing this since this has been already completed and has a merged PR
