### ISSUE TITLE
How to get the totalpage,not just a chapter's

### ISSUE THREAD

**Issue by risechen** [readium/r2-testapp-swift#45]

**Comment by ClassWizard** [comment]
In fact, I just have did some research by myself. I render each html in background, Then get the total pages. It not a perfect method, but it do work, hardly. I'm still waiting for the official implementation by Readium. I'm glad to have some discussion when they ready to do this.
If you choose my way, there are some thing you should notice.
1.  webView may stop the rendering job at some time. But I don't know the reason.
2. the timing of html finish loaded, is hard to catch. (Maybe I choose the wrong way, I firstly try KVO of scrollview's contentSize. It sometimes may not much accuracy.)
3. simply load the html will take much time. Specially when you load some custom fonts.
4. any font family/size change can make the page change. you should recounting.
5. you may want to setup a database to save the pages.

**Comment by mickael-menu** [comment]
This can be done using the new `positionList` API.

Basically you can get the current position index from the last broadcasted `Locator.locations.position`, and the total number of positions is available with `Publication.positionList.count`.

More information here: https://github.com/readium/architecture/issues/101
