### ISSUE TITLE
How to add bookmark？

### ISSUE THREAD

**Issue by risechen** [readium/r2-testapp-swift#46]

**Comment by ClassWizard** [comment]
When closing the publication, the app will save the progression. You could use the same way to add bookmark.

**Comment by llemeurfr** [comment]
Bookmarks are in the readium-2 roadmap, in v1.0.0 ; see https://github.com/readium/readium-2/blob/master/roadmap.md for more info. The implementation relies on the storage of a page progression indicator, that need to be computed using the JS lib (glue.js) which is currently developed by the R2 team. 
We'd be happy if you would help us on the feature.

**Comment by ClassWizard** [comment]
@llemeurfr
Is there any way to find out the exact content(or the first element) of current page(colum) when user making a bookmark?
I'm considering this situation：when users have made some bookmarks, they don't really know what they stand for. If only the read system can autosave some associated content when they making bookmarks. Therefore they can know some brief info about the bookmark. Letting user to Input some description is not very convenience.(in Readium SDK)
If there is no such method, should I do some traverse job to find it? Does it hit much performance？

**Comment by llemeurfr** [comment]
This is an interesting thought, we have to design the bookmark API. Such contextual content could be (part of) the info returned by a bookmark.getContext() method.

**Comment by iaomw** [comment]
For the `content` of bookmark, this is more or less a JavaScript topic, it cannot be done by Swift.
With Javascript code, you can try to get text from visible area, then sent it to Swift code.

I am guessing Kindle did it in such way.
