### ISSUE TITLE
On iOS 9.3.5 (iPad) user settings don't work

### ISSUE THREAD

**Issue by llemeurfr** [readium/r2-testapp-swift#47]
On IOS 9.3.5 (iPad) the user setting menu does not work. Font size, night mode, scroll mode, font size, change font... :(

**Comment by iaomw** [comment]
Looks like JS and CSS are not loaded correctly with WKWebView on iOS 9.

**Comment by aferditamuriqi** [comment]
I am closing this since this has been already completed and has a merged PR
