### ISSUE TITLE
RTL page progression not supported

### ISSUE THREAD

**Issue by rkwright** [readium/r2-testapp-swift#5]
When loading an EPUB which is RTL (e.g [EPUB Test Suite 130](http://epubtest.org/epubs/epub30-test-0130-20160116.epub)), the application does not use the right page progression directions.  Instead, the page progression is LTR, just as in most western books.

*Procedure:*

1. Load the specified test book (above)
2. Page through the book. 

Pages are LTR, not RTL.

Also, in the case of the book above, note that the cover is not properly displayed, but is half off the screen to the left.

*Test Environment:*
R2 Test App 0.2 (2)
iPAD 5
iOS 11.0.3
16 GB memory

**Comment by HadrienGardeur** [comment]
Yeah, RTL support is not available yet in the iOS streamer. Can you open an issue in the streamer if you can't find one related to RTL?

**Comment by rkwright** [comment]
@HadrienGardeur Done.  https://github.com/readium/r2-streamer-swift/issues/42

**Comment by iaomw** [comment]
RTL already supported, as a general issue I will close this. 

The current css code doesn't work well with svg book cover. Waiting for solve.
https://github.com/readium/readium-css/issues/50 

For the fist html(front.xhtml) except book cover, it didn't provided any language information.
