### ISSUE TITLE
"open in.." stopped working in iOS 11.3 

### ISSUE THREAD

**Issue by aferditamuriqi** [readium/r2-testapp-swift#55]
When selecting an LCP file for download, the file is being presented in clear text instead of the selector to choose in which app to open. 

iOS 9.3 - works as expected 
iOS 10.3.1 - works as expected 

ePub files still work as expected on iOS 11.3, 10.3.1, 9.4

**Comment by llemeurfr** [comment]
Solved on the EDRLab website by changing the mime-type associated with .lcpl files. The standard mime-type is application/vnd.readium.lcp.license.v1.0+json. The new value is application/vnd.readium.lcp.license.v1.0.
By suppressing the "+json" suffix, I believe that Safari iOS 11.3 does not infer anymore that the content is json. Therefore does not show the content structure anymore.
We'll keep it as-is to avoid testers to be lost. 

If an .lcpl file is shared via iCloud, the json structure is still displayed when opening it. iCloud must have some sort of automatic parsing of file contents.

**Comment by HadrienGardeur** [comment]
Should this really be closed? 

I don't think that changing the media type in HTTP header is a real fix for this issue.

**Comment by llemeurfr** [comment]
Well, I dont see what we can do really, until iOS takes into account the content-type exposed during an http fetch to guide to a supporting app.

**Comment by aferditamuriqi** [comment]
I believe this is really just an issue on iOS 11.3 and does work properly on any other version since iOS 11.3 just got released I would think that there might be some updates coming. so we should just keep an eye on, there is nothing more we can do at this point.
