### ISSUE TITLE
OPDS: Improve view when listing only publications

### ISSUE THREAD

**Issue by aferditamuriqi** [readium/r2-testapp-swift#57]

**Comment by HadrienGardeur** [comment]
@aferditamuriqi can you provide more details about this one?

**Comment by HadrienGardeur** [comment]
OK, I've renamed this.

This is the case where feed.publications > 0 and feed.navigation.blank? and feed.groups.blank? (sorry for the Ruby-like pseudo code).

Right now, covers are too small, the text below is too large and gets truncated too easily.

We also need loading indicators when loading the view and when scrolling while the next page is loading.

**Comment by aferditamuriqi** [comment]
handled in V1.0.0-beta.4
