### ISSUE TITLE
OPDS: Access Catalog UI needs improvements (current UI won't adjust with rotation)

### ISSUE THREAD

**Issue by aferditamuriqi** [readium/r2-testapp-swift#60]

**Comment by HadrienGardeur** [comment]
This should be handled fairly quickly since this is how we access catalogs in the test app.

**Comment by aferditamuriqi** [comment]
@HadrienGardeur this actually can't be backlogged, this is related to the new issue just created #68 
maybe i should have been more clear in the description of this issue

**Comment by HadrienGardeur** [comment]
OK, well I'll mark this as duplicate #68.
