### ISSUE TITLE
Add document picker to pick book

### ISSUE THREAD

**Issue by iaomw** [readium/r2-testapp-swift#73]
https://developer.apple.com/library/content/documentation/FileManagement/Conceptual/DocumentPickerProgrammingGuide/Introduction/Introduction.html

**Comment by HadrienGardeur** [comment]
I would add that to a settings page that also contains additional info (see #56).

**Comment by iaomw** [comment]
Yes, it should be somewhere. But logically, document picker is not something "settings".

**Comment by llemeurfr** [comment]
I agree with Senda. Pls check with Geoffrey. Where the entry point for OPDS feeds is located (bottom of the screen) and put this call to action here also. Re. UI icons, a plus sign, as in Lisa, does the trick for our test app.

**Comment by aferditamuriqi** [comment]
closing this issue as it has been merged with this PR https://github.com/readium/r2-testapp-swift/pull/122
