### ISSUE TITLE
Advanced setting for system fonts already installed on the system?

### ISSUE THREAD

**Issue by JayPanoz** [readium/r2-testapp-swift#78]
[Original issue can be found on the ReadiumCSS’ issue tracker](https://github.com/readium/readium-css/issues/22)

This is not urgent but the issue belongs to apps and it will be more visible to developers in the apps’ issue tracker.

<blockquote>
<p>Users want to have control to meet their disability, preferences, taste…</p>
<p>Providing a Google fonts install in the reading app is a good thing but what will be better is to provide the list of fonts already aiviable in the system as most of the users would have already installed there their needed fonts.</p>
<p>It needs a work specific for each platform and implementation but will be the best way to provide users an install extra font features.</p>
<p>Most operating systems have a way to install custom fonts at a OS level so why do each app will reinvent the wheel and provide their on way to install font for their own use instead of just letting the user pick in the system installed fonts.</p>
<p>As an example, even iOS which was really close have add a way to install fonts through Apple configurator app and the process is even simpler through http://sub.pentacom.jp/custom-ios-fonts/ or an app like Anyfont. Even font vendors like Myfonts eased the process with an install function directly on the order page.</p>
<p>Before this, each app which want to give this option have done an install in app with the major drawback that the font was only aiviable in the app. Now with system install, all app could browse and pick a font from the system as other OS.</p>
<p>This is an example but most platform have this possibility. Its works to done for each one but this seems the way to go as users willing to install a custom fonts in their reading apps must probably have ever installed it on the system for use in other apps.</p>
</blockquote>

**Comment by HadrienGardeur** [comment]
In general, we need a very short tutorial for adding more fonts to Readium CSS, this will be a super common request from developers.

**Comment by JayPanoz** [comment]
Yeah, especially as we probably don’t want to use CSS there (`@font-face`), which will be a perf-killer, but embed/download fonts in/from the app itself so that they can behave like system fonts.
