### ISSUE TITLE
iPhoneX UI issues 

### ISSUE THREAD

**Issue by aferditamuriqi** [readium/r2-testapp-swift#85]
several issue on iPhoneX
• top and bottom margins 
• scrolling is edge to edge
• TOC 
• bookshelf UI in landscape needs more margin on the hardwar top side

(any other screen should be tested as well)

**Comment by iaomw** [comment]
What is "scrolling is edge to edge"?

**Comment by aferditamuriqi** [comment]
@iaomw I think you addressed edge to edge that by the safe area implementation

**Comment by aferditamuriqi** [comment]
closed by https://github.com/readium/r2-testapp-swift/pull/131
