### ISSUE TITLE
User Settings adaptive UI gets stuck

### ISSUE THREAD

**Issue by aferditamuriqi** [readium/r2-testapp-swift#86]
reproducible steps:
• select user setting panel 
• switch to advanced settings 
• don't switch back, just tap anywhere on the screen for user setting to disappear 
• select user setting panel again
• go back to main settings  and the panel has the taller size and does not adjust

**Comment by iaomw** [comment]
Sorry, because it's using weak reference to popoverPresentationController, the reference disappeared after dismiss the menu. It could be easily solved.
