### ISSUE TITLE
Epub without cover duplicate next cover in library

### ISSUE THREAD

**Issue by garconvacher** [readium/r2-testapp-swift#9]
On a "new instance" (after kill the process):
- import an epub without bitmap cover (e.g. [epub30-test-300](http://epubtest.org/epubs/epub30-test-0300-20170809.epub))
- imported epub duplicates the cover from another epub after displaying the correct front for a short time .
- import one more epub without cover and the display is fine.

![img_0005](https://user-images.githubusercontent.com/24473413/32097646-84325ad6-bb0a-11e7-8ef9-b84ea1e23fcf.PNG)
![img_0006](https://user-images.githubusercontent.com/24473413/32097658-8af41030-bb0a-11e7-8df8-ffa25e59173d.PNG)

**Comment by camill-a** [comment]
Hi,

Thanks for your feedback, I noticed too there was something wrong on the
library but I didn't really work on it yet. I'll look into it.



Alexandre Camilleri
alexcamill@gmail.com
06.38.79.36.42

**Comment by garconvacher** [comment]
By the way, when I kill the process, all the imported epubs disappear.

**Comment by iaomw** [comment]
Thanks for you feedback, it's an interesting problem to see in the beginning. After reviewing the code, I found out it's actually a typical novice problem on iOS when doing some Async update on UICollectionView or UITableView.

Let me explain how does it happened? 

The architecture of Readium 2 is a Client-Server. That means you cannot get book cover immediately in your client code. Even it's local HTTP server, it's not sync. When the order of books has changed, but the app is still trying to update the book cover based on the previous book order. It will happen.

Another reason came from Kingfisher framework and how it was used in the old code. Kingfisher is not bad as Image cache. But there are some bad consequence from the API design of Kingfisher.

With Kingfisher, you can set the image url to imageview, then Kingfisher will do everything for you, including async download, caching, updating the imageview. How doesn't the bug happen with Kingfisher? There is a completion callback from Kingfisher, it will be triggered after the image view already been filled with downloaded or cached image. It's already too late to doing anything here.

```
cell.imageView.kf.setImage(with: coverUrl, placeholder: nil,
                                       options: [.transition(ImageTransition.fade(0.5))],
                                       progressBlock: nil, completionHandler: { error in
                                        cell.applyShadows()
            })
```
So my solution is only using the ImageDownloader and ImageCache from Kingfisher. It will reduce some boring coding work for me. But who knows, the cache didn't work as my expectation, and there are some differences between the real API and document.

Here is a list of what exactly happened for this bug:

- Share the book from other Apps or Airdrop
- App r2-testapp-swift launched
- Start `func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool`
- Prepare 6 demo books
- Load others books under App's document dir
- The Library `UICollectionViewController` is inited with books and loaded
- App started to download book covers for each book cell
- Finish `func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool`
- Start `func application(_ application: UIApplication, open url: URL,
                     sourceApplication: String?, annotation: Any) -> Bool'
- The new book you shared from somewhere is loaded now.
- The new book is sorted as second book in all books
- All book is passed to Library `UICollectionViewController`
- The Library reloaded all books
- You new book appeared at second position
- App just got the book cover of previous second book.
- App updated the book cover of second position which doesn't have book cover.
- You got the strange result
