### ISSUE TITLE
Improve UI for mixed views

### ISSUE THREAD

**Issue by HadrienGardeur** [readium/r2-testapp-swift#93]
There are multiple issues with how the mixed view is currently handled:
- navigation should be grouped together with a generic label on top (something like "browse") using the same design as a group for publications
- covers are way too small in groups containing publications (we should see between 4 and 5 items in portrait on an iPad, not 8)
- groups containing navigation are not handled correctly: the title is displayed but not the content
- all publications listed in `feed.publications` should also be displayed in a group, with `feed.metadata.title` at the title of that group

Here's a screenshot from beta3 displaying the OPDS 2.0 Test Catalog for reference:
![Image uploaded from iOS (14).png](https://images.zenhubusercontent.com/54315b5c04447e47405ce285/ff4aad67-25fc-4ed4-aefa-c522bab1e6eb)

**Comment by aferditamuriqi** [comment]
handled in V1.0.0-beta.4
