### ISSUE TITLE
App Crash when deleting a book from the bookshelf

### ISSUE THREAD

**Issue by aferditamuriqi** [readium/r2-testapp-swift#99]

**Comment by gbugniot** [comment]
Does this crash occur for every books you've tried to delete? I'm not facing this issue.

**Comment by aferditamuriqi** [comment]
Yes, this crash happens with every book. I didn't have a chance to debug anything but noticed this with the current app store release.

**Comment by aferditamuriqi** [comment]
I am closing this issue.
on the devices i was experiencing this crashes i no longer have any crashes after deleting and reinstalling the app
